Unified logging function

diff --git a/scdl b/scdl
--- a/scdl
+++ b/scdl
@@ -12,6 +12,26 @@ function CURL(){ # Just a code shortcut
     curl -L -s --user-agent 'Mozilla/5.0' "$1"
 }
 
+function log() { # Logging function
+	local level
+	level="$1"; shift
+	if [[ "$level" -le "$logVerbosity" ]] ; then
+		case "$level" in
+			0)
+				;;
+			1)
+				echo -n "[e]"; ;;
+			2)
+				echo -n "[w]"; ;;
+			3)
+				echo -n "[i]"; ;;
+			4)
+				echo -n "[d]"; ;;
+		esac
+		echo " $@";
+	fi
+}
+
 function settags() { # Set the mp3 tags
     local artist=$1
     local title=$2
@@ -34,25 +54,25 @@ function settags() { # Set the mp3 tags
             --artist="$artist" -Y $(date +%Y) --genre="$genre" \
             --title="$title" --album="$album" --v2 "$filename" &>/dev/null
 
-        echo '[i] Setting tags finished!'
+        log 3 "Setting tags finished!"
     else
-        echo "[i] Setting tags skipped (please install eyeD3)"
+        log 3 "Setting tags skipped (please install eyeD3)"
     fi
 }
 
 function downsong() { # Parse json for one song
     url="$1"
-    echo "[i] Grabbing artists page"
-    [[ "$debug" == '1' ]] && echo "https://api.soundcloud.com/resolve.json?url=$url&client_id=$clientID"
+    log 3 "Grabbing artists page"
+    log 4 "https://api.soundcloud.com/resolve.json?url=$url&client_id=$clientID"
     songID=$(CURL "https://api.soundcloud.com/resolve.json?url=$url&client_id=$clientID" | tr "," "\n" | sed -n "2p" | cut -d ':' -f 2)
-    [[ "$debug" == '1' ]] && echo "songID is : $songID"
+    log 4 "songID is : $songID"
     fromjsontomp3 "$songID" "$clientID"
 }
 
 function fromjsontomp3 { # use the json to download info and mp3
     clientID="$2"
     songID="$1"
-    [[ "$debug" == '1' ]] && echo "https://api.soundcloud.com/tracks/$songID.json?client_id=$clientID"
+    log 4 "https://api.soundcloud.com/tracks/$songID.json?client_id=$clientID"
     songinfo=$(CURL "https://api.soundcloud.com/tracks/$songID.json?client_id=$clientID" | tr "," "\n")
     title=$(printf "%s\n" "$songinfo" | grep '"title"' | cut -c 10- | rev | cut -c 2- | rev | tr '\/:*?|<>' '________' )
     filename=$(printf "%s\n" "$title.mp3")
@@ -62,10 +82,10 @@ function fromjsontomp3 { # use the json to download info and mp3
     imageurl=$(echo -e "$songinfo" | grep "artwork_url" | cut -d '"' -f 4 | sed 's/large/t500x500/g')
     genre=$(echo -e "$songinfo" | grep "genre" | cut -d '"' -f 4)
     songpermalink=$(echo -e "$songinfo" | grep -m2 "permalink_url" | tail -n1 | cut -d '"' -f 4)
-	[[ "$debug" == '1' ]] && echo "[i] Track permalink_url : $songpermalink"
+	log 4 "[i] Track permalink_url : $songpermalink"
 
     if [ -e "$filename" ]; then
-        echo "[!] The song $filename has already been downloaded..."  && $cont
+        log 1 "The song $filename has already been downloaded..."  && $cont
     else
         echo "[-] Downloading $title..."
         curl -# -L --user-agent 'Mozilla/5.0' -o "`echo -e "$filename"`" "$realsongurl"
@@ -75,36 +95,36 @@ function fromjsontomp3 { # use the json to download info and mp3
 }
 
 function downlike()  { # Parse json for all user's like
-    echo "[i] Grabbing artist's likes page"
+    log 3 "Grabbing artist's likes page"
     artistnm=$(echo "$1" | cut -d '/' -f 4)
     likeurl=$(echo "https://soundcloud.com/$artistnm")
-    [[ "$debug" == '1' ]] && echo "https://api.soundcloud.com/resolve.json?url=$likeurl&client_id=$clientID"
+    log 4 "https://api.soundcloud.com/resolve.json?url=$likeurl&client_id=$clientID"
     artistID=$(CURL "https://api.soundcloud.com/resolve.json?url=$likeurl&client_id=$clientID" | tr "," "\n" | sed -n "1p" | cut -d ':' -f 2)
-    [[ "$debug" == '1' ]] && echo "artistID is : $artistID"
+    log 4 "artistID is : $artistID"
     offset=$default_offset
     likepage=$(CURL "https://api.soundcloud.com/users/$artistID/favorites.json?client_id=$clientID&limit=1&offset=$offset")
     while [[ $(echo "$likepage" | grep 'id') != '' ]]
     do
-        [[ "$debug" == '1' ]] && echo "https://api.soundcloud.com/users/$artistID/favorites.json?client_id=$clientID&limit=1&offset=$offset"
+        log 4 "https://api.soundcloud.com/users/$artistID/favorites.json?client_id=$clientID&limit=1&offset=$offset"
         setsongID=$(echo "$likepage" | tr "," "\n" | grep '"uri"' | grep 'tracks' | cut -d '"' -f 4 | cut -d '/' -f 5)
         ((offset++))
         echo ""
-        echo "[i] Song liked n°$offset by $artistnm"
+        log 3 "Song liked n°$offset by $artistnm"
         fromjsontomp3 "$setsongID" "$clientID"
         likepage=$(CURL "https://api.soundcloud.com/users/$artistID/favorites.json?client_id=$clientID&limit=1&offset=$offset")
     done
     echo ""
-    echo "[i] There was $offset songs."
+    log 3 "There was $offset songs."
 }
 
 function downset() { # Parse json for one user's set
-    [[ "$debug" == '1' ]] && echo "https://api.soundcloud.com/playlists/$playlistID.json?limit=1&offset=$setOffset&client_id=$clientID"
-    echo "[i] Grabbing set page"
+    log 4 "https://api.soundcloud.com/playlists/$playlistID.json?limit=1&offset=$setOffset&client_id=$clientID"
+    log 3 "Grabbing set page"
     url="$1"
     setpage=$(CURL $url)
-    [[ "$debug" == '1' ]] && echo "https://api.soundcloud.com/resolve.json?url=$url&client_id=$clientID"
+    log 4 "https://api.soundcloud.com/resolve.json?url=$url&client_id=$clientID"
     playlistID=$(CURL "https://api.soundcloud.com/resolve.json?url=$url&client_id=$clientID" | tr "," "\n" | grep 'https://api.soundcloud.com/playlists' | cut -d '/' -f 5)
-    [[ "$debug" == '1' ]] && echo "playlistID is : $playlistID"
+    log 4 "playlistID is : $playlistID"
 
     setOffset=0
     setpage=$(CURL "https://api.soundcloud.com/playlists/$playlistID.json?limit=1&offset=$setOffset&client_id=$clientID")
@@ -115,18 +135,18 @@ function downset() { # Parse json for one user's set
         setsongID=$(echo "$setpage" | tr "," "\n" | grep '"uri"' | grep 'tracks' | cut -d '"' -f 4 | cut -d '/' -f 5)
         ((setOffset++))
         echo ""
-        echo "[i] Song n°$setOffset from the Set : $setTitle"
+        log 3 "Song n°$setOffset from the Set : $setTitle"
         fromjsontomp3 "$setsongID" "$clientID"
         setpage=$(CURL "https://api.soundcloud.com/playlists/$playlistID.json?limit=1&offset=$setOffset&client_id=$clientID")
         trackExist=$(echo "$setpage" | tr "," "\n" | grep '"tracks"' | cut -d ':' -f 2)
     done
     echo ""
-    echo "[i] There was $setOffset songs in the set $setTitle."
+    log 3 "There was $setOffset songs in the set $setTitle."
 }
 
 function downallsongs() { # Parse json for all user's songs
     url="$1"
-    echo "[i] Grabbing artists page"
+    log 3 "Grabbing artists page"
     page=$(CURL $url)
     artistID=$(CURL "https://api.soundcloud.com/resolve.json?url=$url&client_id=$clientID" | tr "," "\n" | sed -n "1p" | cut -d ':' -f 2)
     echo ""
@@ -138,12 +158,12 @@ function downallsongs() { # Parse json for all user's songs
         playlist=$(echo "$artistpage" | tr "," "\n" | grep '"playlist"' | cut -c 14-)
         ((offset++))
         if [[ "$playlist" != "null" ]]; then
-            echo "[i] The n°$offset is a playlist"
+            log 3 "The n°$offset is a playlist"
             thisset=$(echo "$artistpage" | tr "," "\n" | grep '"permalink_url"' | sed -n 1p | cut -d '"' -f 4)
             downset "$thisset"
         else
             echo ""
-            echo "[i] Song n°$offset"
+            log 3 "Song n°$offset"
             typesong=$(echo "$artistpage" | tr "," "\n" | grep '"type"' | cut -d '"' -f 4)
             if [[ "$typesong" == "track" ]] && [[ "$onlyrepost" == "0" ]] ; then
                 artistsongurl=$(echo "$artistpage" | tr "," "\n" | grep 'permalink_url' | sed '1d' | cut -d '"' -f 4)
@@ -162,18 +182,18 @@ function downallsongs() { # Parse json for all user's songs
         artistpage=$(CURL "https://api.sndcdn.com/e1/users/$artistID/sounds.json?limit=1&offset=$offset&client_id=$clientID")
     done
     echo ""
-    echo "[i] There was $offset songs/sets."
+    log 3 "There was $offset songs/sets."
 }
 
 function downallsets() { # Parse json for all user's sets
     artistnm=$(echo "$1" | cut -d '/' -f 4)
     seturl=$(echo "https://soundcloud.com/$artistnm")
-    echo "[i] Grabbing artist's set page"
+    log 3 "Grabbing artist's set page"
     page=$(CURL $seturl)
 
-    [[ "$debug" == '1' ]] && echo "https://api.soundcloud.com/resolve.json?url=$seturl&client_id=$clientID"
+    log 4 "https://api.soundcloud.com/resolve.json?url=$seturl&client_id=$clientID"
     artistID=$(CURL "https://api.soundcloud.com/resolve.json?url=$seturl&client_id=$clientID"  | tr "," "\n" | sed -n "1p" | cut -d ':' -f 2)
-    [[ "$debug" == '1' ]] && echo "artistID is : $artistID"
+    log 4 "artistID is : $artistID"
     all_offset=0
     allsetpage=$(CURL "https://api.soundcloud.com/users/$artistID/playlists.json?limit=1&offset=$all_offset&client_id=$clientID")
     while [[ $(echo "$allsetpage" | grep 'id') != '' ]]
@@ -181,24 +201,24 @@ function downallsets() { # Parse json for all user's sets
         thisset=$(echo "$allsetpage" | tr "," "\n" | grep '"permalink_url"'  | sed -n 1p | cut -d '"' -f 4)
         ((all_offset++))
         echo ""
-        echo "[i] Set n°$all_offset from $artistnm"
+        log 3 "Set n°$all_offset from $artistnm"
         downset "$thisset"
-        echo "[i] Set n°$all_offset from $artistnm downloaded"
+        log 3 "Set n°$all_offset from $artistnm downloaded"
         allsetpage=$(CURL "https://api.soundcloud.com/users/$artistID/playlists.json?limit=1&offset=$all_offset&client_id=$clientID")
     done
     echo ""
-    echo "[i] There was $all_offset sets."
+    log 3 "There was $all_offset sets."
 }
 
 function downgroup() { # Parse json for a group
     groupurl="$1"
-    echo "[i] Grabbing group page"
+    log 3 "Grabbing group page"
     groupage=$(CURL "$groupurl")
     groupid=$(echo "$groupage" | grep "html5-code-groups" | tr " " "\n" | grep "html5-code-groups-" | cut -d '"' -f 2 | sed '2d' | cut -d '-' -f 4)
     trackspage=$(CURL "https://api.soundcloud.com/groups/$groupid/tracks.json?client_id=$clientID" | tr "}" "\n")
     trackspage=$(echo "$trackspage" | tr "," "\n" | grep 'permalink_url' | sed '1d' | sed -n '1~2p')
     songcount=$(echo "$trackspage" | wc -l)
-    echo "[i] Found $songcount songs!"
+    log 3 "Found $songcount songs!"
     for (( i=1; i <= $songcount; i++ ))
     do
         echo -e "\n---------- Downloading Song n°$i ----------"
@@ -211,7 +231,7 @@ function downgroup() { # Parse json for a group
 function show_help() { # Display some help
     all=$1
     echo ""
-    echo "[i] Usage: scdl [OPTION] -l [URL]"
+    log 3 "Usage: scdl [OPTION] -l [URL]"
     echo "    With url like :"
     echo "        https://soundcloud.com/user (Download all of one user's songs)"
     echo "        https://soundcloud.com/user/song-name (Download one single song)"
@@ -228,6 +248,7 @@ function show_help() { # Display some help
         echo "  -c              Script will continue if a sound as already been downloaded."
         echo "  -r              Download only the repost."
         echo "  -d              Debug."
+        echo "  -q              Quiet, only warnings and errors."
         echo "  -h              Show this help."
     else
         echo ""
@@ -252,7 +273,7 @@ function get_arg() { # Parse arguments
             o) # Need argument
                 default_offset=$OPTARG
                 if ! [[ $default_offset =~ $number ]] ; then
-                    echo "[!] Offset should be a number"; exit 1
+                    log 1 "Offset should be a number"; exit 1
                 fi
                 ;;
             l) # Need argument
@@ -262,11 +283,14 @@ function get_arg() { # Parse arguments
                 if [ -d "$OPTARG" ]; then
                     pathtomusic="$OPTARG"
                 else
-                    echo '[!] Directory specified does not exist.'; show_help; exit 1
+                    log 1 "Directory specified does not exist."; show_help; exit 1
                 fi
                 ;;
             d) # debug
-                debug=1
+                logVerbosity=4
+                ;;
+            q) # quiet
+                logVerbosity=2
                 ;;
             \?)
                 show_help; exit 1
@@ -274,15 +298,15 @@ function get_arg() { # Parse arguments
         esac
     done
     shift $((OPTIND-1))
-    [[ "$userLink" == '' ]] && echo '[!] You need to specify the URL' && show_help && exit 1
+    [[ "$userLink" == '' ]] && log 1 "You need to specify the URL" && show_help && exit 1
 }
 
 function config() { # Check for the path where download music
     if [ -f "/$HOME/.scdl.cfg" ]; then
         source "/$HOME/.scdl.cfg"
     else
-        echo '[i] The config file do not exist...'
-        echo '[i] Please run the Installer first or add the sample config file'
+        log 1 "The config file does not exist..."
+        log 1 "Please run the Installer first or add the sample config file"
         exit
     fi
 }
@@ -294,12 +318,13 @@ function init() { # Init some variable
     cont=exit
     continue_info='exit'
     number='^[0-9]+$'
+	logVerbosity=3
 }
 
 function check_sys() { # Check system for curl & eyed3
-    command -v curl &>/dev/null || { echo "[!] cURL needs to be installed in order to run the script."; echo "[!] The script will exit..."; exit 1; }
-    command -v eyeD3 &>/dev/null || { echo "[!] eyeD3 needs to be installed to write tags into mp3 file."; echo "[!] The script will skip this part..."; writags=0; }
-    [[ "$debug" == '1' ]] && echo "[i] Using" `curl -V` | cut -c-21
+    command -v curl &>/dev/null || { log 1 "cURL needs to be installed in order to run the script."; log 1 "The script will exit..."; exit 1; }
+    command -v eyeD3 &>/dev/null || { log 1 "eyeD3 needs to be installed to write tags into mp3 file."; log 2 "The script will skip this part..."; writags=0; }
+    log 4 "Using" `curl -V` | cut -c-21
 }
 
 # Launch function
@@ -313,41 +338,41 @@ cd "$pathtomusic"
 
 # Play with the soundcloud url
 soundurl=$(echo "$userLink" | sed 's-.*soundcloud.com/-https://soundcloud.com/-' | cut -d "?" -f 1)
-echo "[i] Using URL : $soundurl"
+log 3 "Using URL : $soundurl"
 d1="$(echo "$soundurl" | cut -d "/" -f 4)"
 d2="$(echo "$soundurl" | cut -d "/" -f 5)"
 d3="$(echo "$soundurl" | cut -d "/" -f 6)"
 
 # Display info of the current configuration
-echo "[i] Path where i will download music : $pathtomusic"
-echo "[i] I will $continue_info if i found a file that already exist"
-[[ "$onlyrepost" == '1' ]] && echo "[i] I will only download reposted sound"
-[[ "$default_offset" != '0' ]] && echo "[i] I will begin the download at $default_offset sound"
-[[ "$debug" == '1' ]] && echo "[i] Using clientID : $clientID"
-[[ "$debug" == '1' ]] && echo "[i] Using "`eyeD3 --version  2>&1 | grep -m1 eye | cut -d " " -f -2`
+log 3 "Path where i will download music : $pathtomusic"
+log 3 "I will $continue_info if i found a file that already exist"
+[[ "$onlyrepost" == '1' ]] && log 3 "I will only download reposted sound"
+[[ "$default_offset" != '0' ]] && log 3 "I will begin the download at $default_offset sound"
+log 4 "Using clientID : $clientID"
+log 4 "Using "`eyeD3 --version  2>&1 | grep -m1 eye | cut -d " " -f -2`
 
 # Choose the right URL type
 if [[ "$d1" == "" ]] ; then
-    echo "[!] Bad URL!"
+    log 1 "Bad URL!"
     show_help
     exit 1
 elif [[ "$d1" == "groups" ]] ; then
-    echo "[i] Detected download type : All song of the group"
+    log 3 "Detected download type : All song of the group"
     downgroup "$soundurl"
 elif [[ "$d2" == "likes" ]] ; then
-    echo "[i] Detected download type : All of one user's like"
+    log 3 "Detected download type : All of one user's like"
     downlike "$soundurl"
 elif [[ "$d2" == "" ]] ; then
-    echo "[i] Detected download type : All of one user's songs"
-    [[ "$onlyrepost" == 1 ]] && echo '[i] Only the repost will be downloaded'
+    log 3 "Detected download type : All of one user's songs"
+    [[ "$onlyrepost" == 1 ]] && log 3 "Only the repost will be downloaded"
     downallsongs "$soundurl"
 elif [[ "$d2" == "sets" ]] && [[ "$d3" == "" ]] ; then
-    echo "[i] Detected download type : All of one user's sets"
+    log 3 "Detected download type : All of one user's sets"
     downallsets "$soundurl"
 elif [[ "$d2" == "sets" ]] ; then
-    echo "[i] Detected download type : One single set"
+    log 3 "Detected download type : One single set"
     downset "$soundurl"
 else
-    echo "[i] Detected download type : One single song"
+    log 3 "Detected download type : One single song"
     downsong "$soundurl"
 fi
